name: CI
on:
  push:
    branches: 
      - main
  pull_request: {}
  workflow_dispatch: {}


jobs:
  # Execute build.sh
  generate_code:
    runs-on: ubuntu-22.04
    container: 
      image: golang:1.20-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Generate code
        run: |
          apk update && apk add git bash make curl openssh-client
          go install golang.org/x/tools/cmd/goimports@latest
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          # check if ssh key is valid
          ssh-keygen -l -f ~/.ssh/id_rsa
          # Create known_hosts
          touch ~/.ssh/known_hosts
          # Add github key to known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # Change permissions to the private key
          chmod 400 ~/.ssh/id_rsa
          # Change permissions to known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod +x generate.sh
          ./generate.sh
