name: CI
on:
  push:
    branches: 
      - main
  pull_request: {}
  workflow_dispatch: {}


jobs:
  # Execute build.sh
  generate_code:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate code
        run: |
          echo ${{ secrets.SSH_DEPLOY_KEY }} > ~/.ssh/id_rsa
          chmod +x build.sh
          ./build.sh
