name: CI
on:
  push:
    branches: 
      - main
  pull_request: {}
  workflow_dispatch: {}


jobs:
  # Execute build.sh
  generate_code:
    runs-on: ubuntu-22.04
    container: 
      image: golang:1.20-alpine
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apk update && apk add git bash make curl openssh-client
          go install golang.org/x/tools/cmd/goimports@latest
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
      - name: Generate code
        run: |
          chmod +x generate.sh
          ./generate.sh
