name: CI
on:
  push:
    branches: 
      - main
  pull_request: {}
  workflow_dispatch: {}


jobs:
  # Execute build.sh
  generate_code:
    runs-on: ubuntu-22.04
    container: 
      image: golang:1.20-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Generate code
        run: |
          apk update && apk add git bash make curl
          go install golang.org/x/tools/cmd/goimports@latest
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          chmod +x generate.sh
          ./generate.sh
